package com.example.halakou.data.local

import com.example.halakou.domain.model.ChatMessage
import com.example.halakou.domain.model.ChatSession
import com.example.halakou.domain.model.LlmProvider
import com.example.halakou.domain.model.MessageRole
import com.example.halakou.domain.model.ToolExecution
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.util.UUID

class ChatHistoryRepository(private val chatDao: ChatDao) {

    val allSessions: Flow<List<ChatSession>> = chatDao.getAllSessionsFlow().map { entities ->
        entities.map { it.toDomain() }
    }

    fun getMessagesForSession(sessionId: String): Flow<List<ChatMessage>> {
        return chatDao.getMessagesForSessionFlow(sessionId).map { entities ->
            entities.map { it.toDomain() }
        }
    }

    suspend fun getMessagesForSessionSync(sessionId: String): List<ChatMessage> {
        return chatDao.getMessagesForSessionSync(sessionId).map { it.toDomain() }
    }

    suspend fun createSession(
        title: String,
        provider: LlmProvider,
        modelId: String
    ): ChatSession {
        val id = UUID.randomUUID().toString()
        val session = ChatSessionEntity(
            id = id,
            title = title,
            provider = provider.id,
            modelId = modelId,
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )
        chatDao.insertSession(session)
        return session.toDomain()
    }

    suspend fun updateSessionTitle(sessionId: String, title: String) {
        chatDao.updateSessionTitle(sessionId, title, System.currentTimeMillis())
    }

    suspend fun togglePinSession(sessionId: String, isPinned: Boolean) {
        chatDao.setSessionPinned(sessionId, isPinned)
    }

    suspend fun deleteSession(sessionId: String) {
        chatDao.deleteSession(sessionId)
    }

    suspend fun saveMessage(message: ChatMessage) {
        chatDao.insertMessage(message.toEntity())
        chatDao.updateSessionTitle(
            sessionId = message.sessionId,
            title = "", // Kept or handled by custom query if needed; we can update updatedAt:
            updatedAt = System.currentTimeMillis()
        )
    }

    suspend fun updateMessage(message: ChatMessage) {
        chatDao.updateMessage(message.toEntity())
    }

    suspend fun exportSessionAsMarkdown(sessionId: String): String {
        val session = chatDao.getSessionById(sessionId) ?: return ""
        val messages = chatDao.getMessagesForSessionSync(sessionId)
        val sb = StringBuilder()
        sb.append("# ${session.title}\n\n")
        sb.append("*Generated by halakou (BYOK AI Client)*\n")
        sb.append("- **Provider:** ${session.provider}\n")
        sb.append("- **Model:** ${session.modelId}\n")
        sb.append("- **Exported on:** ${java.util.Date()}\n\n---\n\n")

        for (msg in messages) {
            val roleHeader = when (msg.role.lowercase()) {
                "user" -> "### 🧑 User"
                "assistant" -> "### 🤖 Assistant (${session.modelId})"
                "tool" -> "### 🛠️ Tool: ${msg.toolName ?: "Agent"}"
                else -> "### System"
            }
            sb.append("$roleHeader\n\n")
            if (!msg.toolName.isNullOrBlank()) {
                sb.append("> **Tool Call:** `${msg.toolName}`\n")
                if (!msg.toolArgs.isNullOrBlank()) {
                    sb.append("> **Arguments:** `${msg.toolArgs}`\n")
                }
                if (!msg.toolResult.isNullOrBlank()) {
                    sb.append("> **Output:**\n> ```\n> ${msg.toolResult.replace("\n", "\n> ")}\n> ```\n\n")
                }
            }
            sb.append("${msg.content}\n\n---\n\n")
        }
        return sb.toString()
    }

    private fun ChatSessionEntity.toDomain(): ChatSession {
        return ChatSession(
            id = id,
            title = title,
            provider = LlmProvider.fromId(provider),
            modelId = modelId,
            createdAt = createdAt,
            updatedAt = updatedAt,
            isPinned = isPinned
        )
    }

    private fun ChatMessageEntity.toDomain(): ChatMessage {
        val roleEnum = when (role.lowercase()) {
            "user" -> MessageRole.USER
            "assistant" -> MessageRole.ASSISTANT
            "tool" -> MessageRole.TOOL
            else -> MessageRole.SYSTEM
        }
        val execution = if (!toolName.isNullOrBlank()) {
            ToolExecution(
                toolName = toolName,
                arguments = toolArgs ?: "",
                result = toolResult,
                isRunning = isToolRunning,
                isError = isToolError
            )
        } else null

        return ChatMessage(
            id = id,
            sessionId = sessionId,
            role = roleEnum,
            content = content,
            toolExecution = execution,
            timestamp = timestamp
        )
    }

    private fun ChatMessage.toEntity(): ChatMessageEntity {
        return ChatMessageEntity(
            id = id,
            sessionId = sessionId,
            role = role.name.lowercase(),
            content = content,
            toolName = toolExecution?.toolName,
            toolArgs = toolExecution?.arguments,
            toolResult = toolExecution?.result,
            isToolRunning = toolExecution?.isRunning ?: false,
            isToolError = toolExecution?.isError ?: false,
            timestamp = timestamp
        )
    }
}
